---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: aidanrt03/iss_tracker:2.0
        container_name: iss_tracker-app
        ports:
            - "5000:5000"
...