---
version: "3"

services:
    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: aidanrt03/iss_tracker_geo:1.0
        container_name: iss_tracker_geo-app
        ports:
            - "5000:5000"
...